# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:

- script: sudo xcode-select --switch /Applications/Xcode_9.3.1.app
  displayName: 'set default xcode to 9.3.1'

- script: xcodebuild -version
  displayName: 'xcode version'

- script: $(which carthage) bootstrap --verbose --platform ios --color auto --cache-builds
  displayName: 'carthage bootstrap'

- script: $(which npm) install
  displayName: 'npm install'

- script: $(which pod) install
  displayName: 'pod install'

- script: $(which npm) run bundle
  displayName: 'npm run bundle'

- script: xcodebuild -workspace Client.xcworkspace -scheme "Fennec" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.3,id=C58C3982-8DDD-4030-9276-C5F30352FCF1" ONLY_ACTIVE_ARCH=NO -derivedDataPath clean build test
  displayName: 'Xcode Build'
